### ISSUE TITLE
テーマごとのウォッチ機能を作成する

### ISSUE THREAD

**Issue by uraki1453** [EastBackCorporation/idea-storming#68]
・テーマ詳細画面でウォッチ登録できる
・ウォッチしているテーマにアイディアが投稿されたらメール通知する
・ダッシュボードにウォッチしているテーマも表示する

**Comment by hiroshi-yamasaki** [comment]
上記と合わせて下記も修正します。

・テーマタイトルの背景色が薄くて文字が映えない。
・テーマを狭くすると見えづらいためUIを見直す。

**Comment by hiroshi-yamasaki** [comment]
![ui](https://user-images.githubusercontent.com/4413090/42608783-5a844750-85c4-11e8-961f-432446847e6a.png)
